version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    volumes:
      - /root/py_pr/bot_db_data:/var/lib/postgresql/data
    env_file:
      - .env

  bot:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: bot_cont
    restart: always
    image: bot_img
    env_file:
      - .env
    depends_on:
      - db
    command: >
      python main.py
